import type { Metadata } from 'next'
import { Manrope } from 'next/font/google'

import '@/shared/styles/style.scss'

const manrope = Manrope({
	subsets: ['latin', 'cyrillic'],
	weight: ['400', '500', '600', '700'],
	display: 'swap',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='ru'>
			<body className={manrope.className}>{children}</body>
		</html>
	)
}
